// بنك أسئلة التدريب المكثّف - 100+ سؤال
// مستويات: easy / medium / hard
// أنواع: numeric / mcq / truefalse

export type PracticeQuestion = {
  id: string;
  lessonId?: string;
  unit?: string;
  grade?: string;
  difficulty: "easy" | "medium" | "hard";
  question: string;
  type: "numeric" | "mcq" | "truefalse";
  options?: string[];
  answer: string;
  explanation: string;
};

export const PRACTICE_QUESTIONS: PracticeQuestion[] = [
  // ====== القياس ======
  {
    id: "p1",
    lessonId: "g9s1-u1-l1",
    unit: "القياس",
    grade: "9",
    difficulty: "easy",
    question: "ما وحدة قياس الكتلة في النظام الدولي SI؟",
    type: "mcq",
    options: ["نيوتن (N)", "كيلوغرام (kg)", "جول (J)", "باسكال (Pa)"],
    answer: "كيلوغرام (kg)",
    explanation: "الكتلة كمية أساسية وحدتها kg في نظام SI.",
  },
  {
    id: "p2",
    lessonId: "g9s1-u1-l1",
    unit: "القياس",
    grade: "9",
    difficulty: "easy",
    question: "حوّل 3.5 km إلى متر.",
    type: "numeric",
    answer: "3500",
    explanation: "كيلو = 10³، إذن 3.5 km = 3.5 × 10³ m = 3500 m.",
  },
  {
    id: "p3",
    lessonId: "g9s1-u1-l1",
    unit: "القياس",
    grade: "9",
    difficulty: "easy",
    question: "البادئة 'ملي' (m) تعادل:",
    type: "mcq",
    options: ["10⁻³", "10⁻⁶", "10³", "10⁻⁹"],
    answer: "10⁻³",
    explanation: "ملي (m) = 10⁻³ مثل الميليمتر = 10⁻³ m.",
  },
  {
    id: "p4",
    lessonId: "g9s1-u1-l1",
    unit: "القياس",
    grade: "9",
    difficulty: "medium",
    question: "كم عدد الأرقام المعنوية في 0.02050؟",
    type: "numeric",
    answer: "4",
    explanation: "الأصفار البادئة غير معنوية، الصفر بين 2 و 5 معنوي، والصفر النهائي بعد 5 معنوي.",
  },
  {
    id: "p5",
    lessonId: "g9s1-u1-l1",
    unit: "القياس",
    grade: "9",
    difficulty: "medium",
    question: "احسب 2.50 × 4.2 بأرقام معنوية صحيحة.",
    type: "numeric",
    answer: "10.5",
    explanation: "2.50 × 4.2 = 10.5. أقل عدد أرقام معنوية هو 2 (من 4.2).",
  },
  {
    id: "p6",
    lessonId: "g9s1-u1-l2",
    unit: "القياس",
    grade: "9",
    difficulty: "easy",
    question: "القيمة الحقيقية = 9.8 m/s² والقيمة المقاسة = 10.0 m/s². ما النسبة المئوية للخطأ؟",
    type: "numeric",
    answer: "2.04",
    explanation: "الخطأ = |10.0 - 9.8| = 0.2. النسبة % = 0.2/9.8 × 100 ≈ 2.04%.",
  },
  {
    id: "p7",
    lessonId: "g9s1-u1-l2",
    unit: "القياس",
    grade: "9",
    difficulty: "medium",
    question: "أداة تعطي قياسات متقاربة جدًا لكن بعيدة عن القيمة الحقيقية، نقول إنها:",
    type: "mcq",
    options: ["دقيقة فقط", "مضبوطة فقط", "دقيقة ومضبوطة", "لا دقيقة ولا مضبوطة"],
    answer: "مضبوطة فقط",
    explanation: "تقارب القياسات المتكررة = ضبط، البعد عن القيمة الحقيقية = عدم الدقة.",
  },
  {
    id: "p8",
    lessonId: "g9s1-u1-l3",
    unit: "القياس",
    grade: "9",
    difficulty: "easy",
    question: "القيمة الحقيقية = 100.0، المقاسة = 98.5. ما الخطأ المطلق؟",
    type: "numeric",
    answer: "1.5",
    explanation: "Δx = |98.5 - 100.0| = 1.5.",
  },
  {
    id: "p9",
    lessonId: "g9s1-u1-l3",
    unit: "القياس",
    grade: "9",
    difficulty: "medium",
    question: "أي نوع من الأخطاء يحدث دائمًا في نفس الاتجاه؟",
    type: "mcq",
    options: ["الخطأ العشوائي", "الخطأ النظامي", "الخطأ الصفري", "خطأ القراءة"],
    answer: "الخطأ النظامي",
    explanation: "الخطأ النظامي يحدث في اتجاه ثابت بسبب خلل في الجهاز أو طريقة الاستخدام.",
  },

  // ====== قوانين نيوتن ======
  {
    id: "p10",
    lessonId: "g9s1-u2-l1",
    unit: "القوى والحركة",
    grade: "9",
    difficulty: "easy",
    question: "احسب تسارع جسم كتلته 5 kg تحت قوة محصلة 20 N.",
    type: "numeric",
    answer: "4",
    explanation: "a = F/m = 20/5 = 4 m/s².",
  },
  {
    id: "p11",
    lessonId: "g9s1-u2-l1",
    unit: "القوى والحركة",
    grade: "9",
    difficulty: "easy",
    question: "وزن جسم كتلته 10 kg على الأرض (g = 9.8 m/s²):",
    type: "numeric",
    answer: "98",
    explanation: "F_g = m·g = 10 × 9.8 = 98 N.",
  },
  {
    id: "p12",
    lessonId: "g9s1-u2-l1",
    unit: "القوى والحركة",
    grade: "9",
    difficulty: "medium",
    question: "قطار يبدأ من السكون، تزداد سرعته إلى 20 m/s بعد 16 s. ما تسارعه؟",
    type: "numeric",
    answer: "1.25",
    explanation: "a = (v_f - v_i)/Δt = (20 - 0)/16 = 1.25 m/s².",
  },
  {
    id: "p13",
    lessonId: "g9s1-u2-l1",
    unit: "القوى والحركة",
    grade: "9",
    difficulty: "easy",
    question: "ينص القانون الأول لنيوتن على أن الجسم يحافظ على حالته الحركية إذا كانت:",
    type: "mcq",
    options: ["القوة المحصلة = صفر", "القوة المحصلة = كتلته", "التسارع ≠ صفر", "السرعة = صفر"],
    answer: "القوة المحصلة = صفر",
    explanation: "عندما F_محصلة = 0، يبقى الجسم ساكنًا أو يتحرك بسرعة ثابتة.",
  },
  {
    id: "p14",
    lessonId: "g9s1-u2-l1",
    unit: "القوى والحركة",
    grade: "9",
    difficulty: "hard",
    question: "صح أم خطأ: قوة الفعل ورد الفعل تلغي إحداهما الأخرى.",
    type: "truefalse",
    options: ["صحيح", "خطأ"],
    answer: "خطأ",
    explanation: "القوتان تؤثران في جسمين مختلفين، فلا تلغي إحداهما الأخرى.",
  },
  {
    id: "p15",
    lessonId: "g9s1-u2-l2",
    unit: "القوى والحركة",
    grade: "9",
    difficulty: "medium",
    question: "احسب القوة العمودية لجسم كتلته 5 kg على سطح أفقي (g = 9.8).",
    type: "numeric",
    answer: "49",
    explanation: "F_N = m·g = 5 × 9.8 = 49 N.",
  },
  {
    id: "p16",
    lessonId: "g9s1-u2-l2",
    unit: "القوى والحركة",
    grade: "9",
    difficulty: "medium",
    question: "إذا كانت F_N = 100 N و μ_k = 0.4، ما قوة الاحتكاك الحركي؟",
    type: "numeric",
    answer: "40",
    explanation: "f_k = μ_k · F_N = 0.4 × 100 = 40 N.",
  },

  // ====== الشغل والقدرة ======
  {
    id: "p17",
    lessonId: "g9s1-u3-l1",
    unit: "الشغل والآلات البسيطة",
    grade: "9",
    difficulty: "easy",
    question: "احسب الشغل المبذول بقوة 30 N على مسافة 4 m.",
    type: "numeric",
    answer: "120",
    explanation: "W = F·d = 30 × 4 = 120 J.",
  },
  {
    id: "p18",
    lessonId: "g9s1-u3-l1",
    unit: "الشغل والآلات البسيطة",
    grade: "9",
    difficulty: "medium",
    question: "إذا بُذل شغل 500 J في 10 s، ما القدرة؟",
    type: "numeric",
    answer: "50",
    explanation: "P = W/t = 500/10 = 50 W.",
  },
  {
    id: "p19",
    lessonId: "g9s1-u3-l1",
    unit: "الشغل والآلات البسيطة",
    grade: "9",
    difficulty: "easy",
    question: "ما الطاقة الحركية لجسم كتلته 2 kg وسرعته 10 m/s؟",
    type: "numeric",
    answer: "100",
    explanation: "K = ½ m v² = ½ × 2 × 100 = 100 J.",
  },
  {
    id: "p20",
    lessonId: "g9s1-u3-l2",
    unit: "الشغل والآلات البسيطة",
    grade: "9",
    difficulty: "medium",
    question: "احسب الفائدة الميكانيكية لآلة ترفع مقاومة 400 N بقوة 100 N.",
    type: "numeric",
    answer: "4",
    explanation: "MA = F_R / F_E = 400 / 100 = 4.",
  },

  // ====== الموائع ======
  {
    id: "p21",
    lessonId: "g9s2-u4-l1",
    unit: "ميكانيكا الموائع",
    grade: "9",
    difficulty: "medium",
    question: "احسب ضغط ماء (ρ = 1000) على عمق 5 m (g = 9.8).",
    type: "numeric",
    answer: "49000",
    explanation: "P = ρ·g·h = 1000 × 9.8 × 5 = 49,000 Pa = 49 kPa.",
  },
  {
    id: "p22",
    lessonId: "g9s2-u4-l2",
    unit: "ميكانيكا الموائع",
    grade: "9",
    difficulty: "medium",
    question: "احسب قوة الدفع على جسم حجمه 0.01 m³ مغمور كليًّا في الماء (ρ = 1000، g = 9.8).",
    type: "numeric",
    answer: "98",
    explanation: "F_B = ρ·g·V = 1000 × 9.8 × 0.01 = 98 N.",
  },
  {
    id: "p23",
    lessonId: "g9s2-u4-l2",
    unit: "ميكانيكا الموائع",
    grade: "9",
    difficulty: "hard",
    question: "ارتفاع الزئبق في بارومتر عند سطح البحر يساوي تقريبًا:",
    type: "mcq",
    options: ["0.5 m", "0.76 m", "1 m", "10 m"],
    answer: "0.76 m",
    explanation: "الضغط الجوي القياسي يرفع الزئبق لارتفاع 760 mm = 0.76 m.",
  },

  // ====== الضوء ======
  {
    id: "p24",
    lessonId: "g9s2-u5-l1",
    unit: "انكسار الضوء وتطبيقاته",
    grade: "9",
    difficulty: "medium",
    question: "احسب سرعة الضوء في الماء (n = 1.33، c = 3×10⁸ m/s). النتيجة بـ 10⁸ m/s.",
    type: "numeric",
    answer: "2.26",
    explanation: "v = c/n = 3×10⁸ / 1.33 ≈ 2.26×10⁸ m/s.",
  },
  {
    id: "p25",
    lessonId: "g9s2-u5-l1",
    unit: "انكسار الضوء وتطبيقاته",
    grade: "9",
    difficulty: "easy",
    question: "عندما ينتقل الضوء من الماء إلى الهواء، فإن زاوية الانكسار:",
    type: "mcq",
    options: ["أكبر من زاوية السقوط", "أقل من زاوية السقوط", "تساويها", "صفر"],
    answer: "أكبر من زاوية السقوط",
    explanation: "من وسط أكثف إلى أقل كثافة، يبتعد الشعاع عن العمود.",
  },
  {
    id: "p26",
    lessonId: "g9s2-u5-l2",
    unit: "انكسار الضوء وتطبيقاته",
    grade: "9",
    difficulty: "hard",
    question: "احسب الزاوية الحرجة للزجاج-الهواء (n_زجاج = 1.5، n_هواء = 1).",
    type: "numeric",
    answer: "41.8",
    explanation: "sin(θ_c) = 1/1.5 = 0.667، θ_c = sin⁻¹(0.667) ≈ 41.8°.",
  },
  {
    id: "p27",
    lessonId: "g9s2-u5-l3",
    unit: "انكسار الضوء وتطبيقاته",
    grade: "9",
    difficulty: "medium",
    question: "جسم على بعد 20 cm من عدسة f = 10 cm. ما بعد الصورة d_i؟",
    type: "numeric",
    answer: "20",
    explanation: "1/d_i = 1/10 - 1/20 = 1/20، d_i = 20 cm.",
  },

  // ====== المتجهات ======
  {
    id: "p28",
    lessonId: "g10s1-u1-l1",
    unit: "المتجهات",
    grade: "10",
    difficulty: "medium",
    question: "متجه قوته 8 N يصنع زاوية 30° مع الأفقي. ما مركبته الأفقية؟",
    type: "numeric",
    answer: "6.93",
    explanation: "A_x = 8 × cos(30°) = 8 × 0.866 ≈ 6.93 N.",
  },
  {
    id: "p29",
    lessonId: "g10s1-u1-l1",
    unit: "المتجهات",
    grade: "10",
    difficulty: "easy",
    question: "متجه مركباته (6, 8). ما مقداره؟",
    type: "numeric",
    answer: "10",
    explanation: "|A| = √(6² + 8²) = √100 = 10.",
  },
  {
    id: "p30",
    lessonId: "g10s1-u1-l2",
    unit: "المتجهات",
    grade: "10",
    difficulty: "medium",
    question: "متجهان |A| = 6، |B| = 8 متعامدان. ما مقدار المحصلة؟",
    type: "numeric",
    answer: "10",
    explanation: "|R| = √(6² + 8²) = √100 = 10.",
  },

  // ====== الحركة ======
  {
    id: "p31",
    lessonId: "g10s1-u2-l1",
    unit: "الحركة والقوى",
    grade: "10",
    difficulty: "easy",
    question: "احسب v_f لسيارة v_i = 5 m/s، a = 3 m/s²، t = 4 s.",
    type: "numeric",
    answer: "17",
    explanation: "v_f = v_i + a·t = 5 + 3×4 = 17 m/s.",
  },
  {
    id: "p32",
    lessonId: "g10s1-u2-l1",
    unit: "الحركة والقوى",
    grade: "10",
    difficulty: "medium",
    question: "جسم يسقط من السكون من ارتفاع 19.6 m (g = 9.8). ما زمن السقوط؟",
    type: "numeric",
    answer: "2",
    explanation: "Δx = ½·g·t²، 19.6 = ½×9.8×t²، t² = 4، t = 2 s.",
  },
  {
    id: "p33",
    lessonId: "g10s1-u2-l2",
    unit: "الحركة والقوى",
    grade: "10",
    difficulty: "medium",
    question: "قذيفة v₀ = 20 m/s، θ = 30°. ما المركبة الرأسية للسرعة الابتدائية؟",
    type: "numeric",
    answer: "10",
    explanation: "v_y = v₀·sin(30°) = 20 × 0.5 = 10 m/s.",
  },
  {
    id: "p34",
    lessonId: "g10s1-u2-l2",
    unit: "الحركة والقوى",
    grade: "10",
    difficulty: "hard",
    question: "ما الزاوية التي تعطي أقصى مدى لمقذوف؟",
    type: "mcq",
    options: ["30°", "45°", "60°", "90°"],
    answer: "45°",
    explanation: "R = v₀²·sin(2θ)/g، أقصى قيمة عند sin(2θ) = 1، أي θ = 45°.",
  },
  {
    id: "p35",
    lessonId: "g10s1-u2-l3",
    unit: "الحركة والقوى",
    grade: "10",
    difficulty: "medium",
    question: "كتلة 10 kg على سطح مائل 30° (بدون احتكاك، g=9.8). ما تسارعها؟",
    type: "numeric",
    answer: "4.9",
    explanation: "a = g·sin(θ) = 9.8 × sin(30°) = 9.8 × 0.5 = 4.9 m/s².",
  },
  {
    id: "p36",
    lessonId: "g10s1-u2-l3",
    unit: "الحركة والقوى",
    grade: "10",
    difficulty: "hard",
    question: "سيارة 800 kg تدور في دائرة r=40 m بـ v=10 m/s. ما القوة المركزية؟",
    type: "numeric",
    answer: "2000",
    explanation: "F_c = m·v²/r = 800 × 100 / 40 = 2000 N.",
  },

  // ====== الجاذبية وتطبيقات نيوتن ======
  {
    id: "p37",
    lessonId: "g10s2-u4-l1",
    unit: "تطبيقات على قوانين نيوتن",
    grade: "10",
    difficulty: "hard",
    question: "احسب g على كوكب كتلته 6×10²⁴ kg ونصف قطره 6×10⁶ m (G = 6.67×10⁻¹¹).",
    type: "numeric",
    answer: "11.1",
    explanation: "g = G·M/R² = 6.67×10⁻¹¹ × 6×10²⁴ / (6×10⁶)² ≈ 11.1 m/s².",
  },
  {
    id: "p38",
    lessonId: "g10s2-u4-l1",
    unit: "تطبيقات على قوانين نيوتن",
    grade: "10",
    difficulty: "easy",
    question: "إذا كانت الكتلة 50 kg على الأرض، ما كتلتها على القمر؟",
    type: "numeric",
    answer: "50",
    explanation: "الكتلة ثابتة لا تتغير بتغير المكان.",
  },
  {
    id: "p39",
    lessonId: "g10s2-u4-l2",
    unit: "تطبيقات على قوانين نيوتن",
    grade: "10",
    difficulty: "medium",
    question: "في نظام Atwood m₁=2 kg، m₂=4 kg، g=10. ما التسارع؟",
    type: "numeric",
    answer: "3.33",
    explanation: "a = (m₂-m₁)·g/(m₁+m₂) = 2×10/6 ≈ 3.33 m/s².",
  },
  {
    id: "p40",
    lessonId: "g10s2-u4-l3",
    unit: "تطبيقات على قوانين نيوتن",
    grade: "10",
    difficulty: "hard",
    question: "قمر ميكانيكي كتلته 100 kg يدور بـ v=10 m/s في r=5 m. ما القوة المركزية؟",
    type: "numeric",
    answer: "2000",
    explanation: "F_c = m·v²/r = 100 × 100 / 5 = 2000 N.",
  },

  // ====== الموائع (10) ======
  {
    id: "p41",
    lessonId: "g10s2-u5-l1",
    unit: "الموائع",
    grade: "10",
    difficulty: "medium",
    question: "احسب الضغط الكلي على عمق 5 m في ماء (ρ=1000، g=9.8، P_atm=101325).",
    type: "numeric",
    answer: "150325",
    explanation: "P = 101325 + 1000×9.8×5 = 150,325 Pa.",
  },
  {
    id: "p42",
    lessonId: "g10s2-u5-l1",
    unit: "الموائع",
    grade: "10",
    difficulty: "easy",
    question: "إذا كانت كثافة الجسم 800 kg/m³ وكثافة الماء 1000، ما نسبة الجزء المغمور؟",
    type: "numeric",
    answer: "80",
    explanation: "نسبة الجزء المغمور = ρ_الجسم/ρ_المائع = 800/1000 = 0.8 = 80%.",
  },
  {
    id: "p43",
    lessonId: "g10s2-u5-l2",
    unit: "الموائع",
    grade: "10",
    difficulty: "medium",
    question: "أنبوب A=0.1 m²، v=4 m/s يضيق إلى A=0.02 m². ما v₂؟",
    type: "numeric",
    answer: "20",
    explanation: "v₂ = A₁·v₁/A₂ = 0.1×4/0.02 = 20 m/s.",
  },
  {
    id: "p44",
    lessonId: "g10s2-u5-l2",
    unit: "الموائع",
    grade: "10",
    difficulty: "easy",
    question: "حسب برنولي، عندما تزداد سرعة المائع:",
    type: "mcq",
    options: ["يزداد الضغط", "يقل الضغط", "يبقى الضغط ثابتًا", "يصبح الضغط صفرًا"],
    answer: "يقل الضغط",
    explanation: "P + ½ρv² = ثابت، علاقة عكسية بين P و v.",
  },

  // ====== الموجات ======
  {
    id: "p45",
    lessonId: "g10s2-u6-l1",
    unit: "الحركة الموجية",
    grade: "10",
    difficulty: "easy",
    question: "موجة λ=4 m، f=10 Hz. ما سرعتها؟",
    type: "numeric",
    answer: "40",
    explanation: "v = λ·f = 4 × 10 = 40 m/s.",
  },
  {
    id: "p46",
    lessonId: "g10s2-u6-l1",
    unit: "الحركة الموجية",
    grade: "10",
    difficulty: "medium",
    question: "ضوء λ = 500 nm، c = 3×10⁸. ما تردده؟ (بـ 10¹⁴ Hz)",
    type: "numeric",
    answer: "6",
    explanation: "f = c/λ = 3×10⁸ / 500×10⁻⁹ = 6×10¹⁴ Hz.",
  },
  {
    id: "p47",
    lessonId: "g10s2-u6-l1",
    unit: "الحركة الموجية",
    grade: "10",
    difficulty: "easy",
    question: "أي مما يلي موجة مستعرضة؟",
    type: "mcq",
    options: ["الصوت في الهواء", "الضوء", "الموجات الزلزالية P", "الموجات الصوتية تحت الماء"],
    answer: "الضوء",
    explanation: "الضوء موجة مستعرضة، الصوت موجة طولية في الهواء.",
  },
  {
    id: "p48",
    lessonId: "g10s2-u6-l2",
    unit: "الحركة الموجية",
    grade: "10",
    difficulty: "hard",
    question: "مصدر صوت بتردد 500 Hz يقترب بسرعة 20 m/s (v=340). ما f'؟",
    type: "numeric",
    answer: "531.25",
    explanation: "f' = 500 × 340/(340-20) = 500 × 340/320 = 531.25 Hz.",
  },
  {
    id: "p49",
    lessonId: "g10s2-u6-l2",
    unit: "الحركة الموجية",
    grade: "10",
    difficulty: "medium",
    question: "تداخل بنّاء يحدث عندما يكون فرق المسار:",
    type: "mcq",
    options: ["نصف طول موجي", "ربع طول موجي", "مضاعفات الطول الموجي", "صفر فقط"],
    answer: "مضاعفات الطول الموجي",
    explanation: "Δr = nλ لتداخل بنّاء (n = 0, 1, 2, ...).",
  },
  {
    id: "p50",
    lessonId: "g10s2-u6-l2",
    unit: "الحركة الموجية",
    grade: "10",
    difficulty: "easy",
    question: "ظاهرة دوبلر تظهر في:",
    type: "mcq",
    options: ["الصوت فقط", "الضوء فقط", "كل الموجات", "الموجات الميكانيكية فقط"],
    answer: "كل الموجات",
    explanation: "دوبلر تحدث مع أي موجة (صوت، ضوء، موجات ماء).",
  },
];

// اختيار سؤال التحدي اليومي بناءً على التاريخ
export function getDailyChallenge(date: Date = new Date()): PracticeQuestion {
  const dayOfYear = Math.floor(
    (date.getTime() - new Date(date.getFullYear(), 0, 0).getTime()) / 86400000
  );
  const idx = dayOfYear % PRACTICE_QUESTIONS.length;
  return PRACTICE_QUESTIONS[idx];
}

export function getTodayKey(date: Date = new Date()): string {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(
    date.getDate()
  ).padStart(2, "0")}`;
}
